### ISSUE TITLE
A problem with annotation for "add_url_rule"

### ISSUE THREAD

**Issue by wenbo1188** [greyli/flask-origin#1]
- I've been reading your annotation for source code of Flask-0.1. And I found maybe something wrong with the function "add_url_rule".

- I check the original version of api annotation in [http://docs.jinkan.org/docs/flask/api.html#id2](http://docs.jinkan.org/docs/flask/api.html#id2)

- It says

        Basically this example:

        @app.route('/')
        def index():
            pass
        Is equivalent to the following:

        def index():
            pass
        app.add_url_rule('/', 'index', index)

- But in your annotation it says

        基本示例：

            @app.route('/')
            def index():
                pass

        和下面相同：

            def index():
                pass
            app.add_url_rule('index', '/')
            app.view_functions['index'] = index

- The sequence of param rule and endpoint is wrong. Maybe it;s a mistake in writing?

**Comment by greyli** [comment]
Thanks for the feedback! It's a mistake from the raw [flask.py](https://github.com/pallets/flask/blob/0.1/flask.py#L404), I will fix it as soon as possible.  If the next time you find something wrong, just propose a PR :)
